### ISSUE TITLE
3j symbols differ compared to sympy

### ISSUE THREAD

**Issue by mersennez** [fujiisoup/py3nj#5]
w3j(l,1,l+1,0,0,0) = 0; in sympy value is not zero (which is correct)

**Comment by fujiisoup** [comment]
py3nj.wigner3j requires integer arguments multiplied by 2.

If you want to copute w3j(l,1,l+1,0,0,0), you need `py3nj.wigner3j(2*l, 2, 2*l + 2, 0, 0, 0)`.

**Comment by mersennez** [comment]
Ok, thanks!
